### PR TITLE
Replace generic index with readable const

### PR DESCRIPTION
**Pull request by DeusExM4ch1n4**

### CODE REVIEW

**Review by un7c0rn — CHANGES_REQUESTED** [review]
@DeusExM4ch1n4 This looks good but won't update the commit message on the contracts directory, you'll need to also update a file within that folder––consider revising or improving a comment somewhere to bump the commit hash.

**Comment by DeusExM4ch1n4** [comment]
@un7c0rn tests/ is within contracts/ 
https://github.com/formless-eng/share-v1-core/commit/0b590251f4b3d62306c9f70a03cffde5bbf397fb

The commit comes from a singular change I made within this same file, it should overwrite this commit in the GH UI. Am I missing something?

**Review by un7c0rn — APPROVED** [review]
LGTM

**Comment by un7c0rn** [comment]
@DeusExM4ch1n4 Ah, you're right. LGTM

**Pull request merged**
